[package]
name = "wayland-info-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
wayland-client = "0.31.12"
wayland-protocols = { version = "0.32.9", features = ["staging", "unstable", "client"] }
